FROM python:3.8-slim-buster  


WORKDIR /flask-docker

RUN python3 -m pip install --upgrade pip  


COPY requirements.txt requirements.txt   
 # copy the requirement file into flask-docker directory in slim buster 


 


